blockExoticSubdeps: true
# 7 days
minimumReleaseAge: 10080

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "esbuild"
  - sharp
  - "vue-demi"
  - workerd
preferFrozenLockfile: true
trustPolicy: no-downgrade
